# setup
setup: scan

# Loss
criterion: scan
criterion_kwargs:
   # entropy_weight: 5.0
   # entropy_weight: 1.0
   entropy_weight: 0.1

# Weight update
update_cluster_head_only: False # Update full network in SCAN
num_heads: 1 # Only use one head

# Dataset
train_db_name: retinopathy
val_db_name: retinopathy
num_classes: 7
num_neighbors: 20

# Transformations
augmentation_strategy: ours 
augmentation_kwargs:
   crop_size: 64
   normalize:
      mean: [0.485, 0.456, 0.406]
      std: [0.229, 0.224, 0.225]
   num_strong_augs: 4
   cutout_kwargs:
     n_holes: 1
     length: 16
     random: True

transformation_kwargs:
   crop_size: 64
   normalize:
      mean: [0.485, 0.456, 0.406]
      std: [0.229, 0.224, 0.225]

# Hyperparameters
optimizer: adam
optimizer_kwargs:
   lr: 0.00001
   weight_decay: 0.0001
epochs: 100
batch_size: 128
num_workers: 8

# Scheduler
scheduler: constant
